spring:
  application:
    name: eureka-server
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30s

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
